spring.application.name=websecurity

#mongodb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=websecurity

#spring.security.user.name=admin
#spring.security.user.password=admin

application.security.jwt.secret-key=U2VjdXJlS2V5QWJjZGVmZ2HP4AW6TD4SSW5F3AGW4AWE7QS3GW6EYG
application.security.jwt.expiration=86400000